apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ toYaml .Values.accountId }}:role/{{ .Values.environment }}_cluster_crossplane_eks_sa
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: provider-aws
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: provider-aws
spec:
  package: crossplane/provider-aws:v0.24.1
  controllerConfigRef:
    name: aws-config
#---
#apiVersion: aws.jet.crossplane.io/v1alpha1
#kind: ProviderConfig
#metadata:
#  annotations:
#    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#  name: provider-aws-jet
#spec:
#  credentials:
#    source: InjectedIdentity
#---
#apiVersion: pkg.crossplane.io/v1
#kind: Provider
#metadata:
#  annotations:
#    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#  name: provider-aws-jet
#spec:
#  package: crossplane/provider-jet-aws:v0.4.0-preview
#  controllerConfigRef:
#    name: aws-config
