---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-creds
      key: creds
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: provider-aws
spec:
  package: crossplane/provider-aws:v0.24.1
#  controllerConfigRef:
#    name: aws-config

